-- 'CAST' helps us specify the number of digits after the comma.

SELECT DATE_, BRANCH, SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY DATE_, BRANCH
ORDER BY SUM(LINENET) DESC, DATE_ ASC


SELECT DATE_, BRANCH, CAST(SUM(LINENET) AS DECIMAL(18, 2)) AS TOPLAMSATIS
FROM SALES
GROUP BY DATE_, BRANCH
ORDER BY SUM(LINENET) DESC, DATE_ ASC

SELECT DATE_, BRANCH, CAST(SUM(LINENET) AS DECIMAL(18, 2)) AS TOPLAMSATIS
FROM SALES
WHERE DATE_ = '20170105'
GROUP BY DATE_, BRANCH
ORDER BY SUM(LINENET) DESC, DATE_ ASC

