Because ASC (ascending) is the default.

SELECT * FROM CUSTOMER
WHERE City = 'Elazığ'
ORDER BY CustomerName

SELECT * FROM CUSTOMER
WHERE City = 'Elazığ'
ORDER BY CustomerName Asc

SELECT * FROM CUSTOMER
WHERE City = 'Elazığ'
ORDER BY CustomerName Desc


SELECT DISTINCT CITY
FROM CUSTOMER
ORDER BY CITY ASC


SELECT CUSTOMERNAME, AGE
FROM CUSTOMER
ORDER BY AGE DESC


SELECT CUSTOMERNAME, AGE, CITY
FROM CUSTOMER
ORDER BY AGE ASC, CITY DESC


SELECT CUSTOMERNAME, AGE, CITY, BIRTHDATE
FROM CUSTOMER
ORDER BY BIRTHDATE ASC


SELECT *
FROM CUSTOMER
ORDER BY 5

-- The fifth column is BIRTHDATE


SELECT *
FROM CUSTOMER
ORDER BY 1,8

-- The first column is ID, and the eighth column is AGE


SELECT CustomerName, Age, City
FROM CUSTOMER
ORDER BY Age ASC, City DESC


SELECT *
FROM CUSTOMER
ORDER BY 3 DESC
-- The 3rd column is City


SELECT *
FROM CUSTOMER
ORDER BY 3 DESC, 4 DESC
-- The 3rd column is City and 4th column is District

