SELECT SUM(LINENET)
FROM SALES
WHERE BRANCH = 'Kocaeli Subesi'


SELECT SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI, MIN(LINENET) AS ENDUSUKFIYAT, MAX(LINENET) AS ENYUKSEKFIYAT, AVG(LINENET) AS ORTALAMASATIS
FROM SALES
WHERE BRANCH = 'Kocaeli Subesi'



SELECT SUM(LINENET) TOPLAMSATIS, COUNT(*) SATIRSAYISI, MIN(LINENET) ENDUSUKFIYAT, MAX(LINENET) ENYUKSEKFIYAT, AVG(LINENET) AS ORTALAMASATIS
FROM SALES
WHERE BRANCH = 'Kocaeli Subesi'
